# Generated by Django 4.2.8 on 2023-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
